# Generated by Django 6.0.5 on 2026-06-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, error_messages={'unique': '该用户名已被使用'}, max_length=60, unique=True),
        ),
    ]
