# Generated by Django 6.0.5 on 2026-08-10 15:46

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, error_messages={'unique': '该用户名已被使用'}, max_length=60, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator(message='用户名只能包含字母、数字和 @/./+/-/_ 字符')]),
        ),
    ]
