# Generated by Django 6.0.5 on 2026-06-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=20, unique=True, verbose_name='菜单唯一标识')),
                ('label', models.CharField(max_length=50, verbose_name='菜单名称')),
                ('path', models.CharField(max_length=250, verbose_name='跳转路径')),
                ('category', models.CharField(choices=[('main', '主导航栏'), ('profile', '个人中心导航栏')], default='main', max_length=20, verbose_name='菜单分类')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序（越小越靠前）')),
                ('match_paths', models.JSONField(blank=True, default=list, verbose_name='匹配路径集')),
            ],
            options={
                'verbose_name': '导航菜单',
                'verbose_name_plural': '导航菜单',
                'ordering': ['sort_order'],
            },
        ),
    ]
