# Generated by Django 6.0.5 on 2026-07-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='描述')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='轮播图图片')),
                ('link', models.URLField(blank=True, max_length=500, verbose_name='跳转链接')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序（越小越靠前）')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
