# Generated by Django 6.0.5 on 2026-07-07 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormulaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='标签名称')),
                ('color', models.CharField(default='#1890ff', max_length=7, verbose_name='标签颜色')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'formula_formula_tag',
            },
        ),
        migrations.CreateModel(
            name='CubeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=3, verbose_name='阶数')),
                ('method', models.CharField(max_length=50, verbose_name='求解方法')),
                ('phase', models.CharField(max_length=50, verbose_name='阶段')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'formula_cube_category',
                'ordering': ['order', 'method', 'sort_order'],
                'unique_together': {('order', 'method', 'phase')},
            },
        ),
        migrations.CreateModel(
            name='CubeState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='状态名称')),
                ('state_definition', models.JSONField(verbose_name='状态定义')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='states', to='formula.cubecategory')),
            ],
            options={
                'db_table': 'formula_cube_state',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='公式名称')),
                ('notation', models.TextField(verbose_name='公式记号')),
                ('inverse_notation', models.TextField(blank=True, verbose_name='逆公式')),
                ('pre_state_definition', models.JSONField(blank=True, null=True, verbose_name='前置状态定义')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='formula_thumbnails/', verbose_name='缩略图')),
                ('difficulty', models.IntegerField(default=1, verbose_name='难度等级')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_custom', models.BooleanField(default=False, verbose_name='是否自定义')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formulas', to='formula.cubecategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_formulas', to=settings.AUTH_USER_MODEL)),
                ('target_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_formulas', to='formula.cubestate')),
            ],
            options={
                'db_table': 'formula_formula',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FormulaCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='formula.formula')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formula_collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'formula_formula_collection',
                'unique_together': {('user', 'formula')},
            },
        ),
        migrations.CreateModel(
            name='FormulaTagRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_relations', to='formula.formula')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formula_relations', to='formula.formulatag')),
            ],
            options={
                'db_table': 'formula_formula_tag_relation',
                'unique_together': {('formula', 'tag')},
            },
        ),
    ]
