# Generated by Django 6.0.5 on 2026-07-19 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='浏览次数'),
        ),
    ]
