# Generated by Django 6.0.5 on 2026-07-24 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0002_formula_view_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cubecategory',
            options={'ordering': ['order', 'method', 'sort_order'], 'verbose_name': '魔方分类', 'verbose_name_plural': '魔方分类'},
        ),
        migrations.AlterModelOptions(
            name='cubestate',
            options={'ordering': ['category', 'name'], 'verbose_name': '魔方状态', 'verbose_name_plural': '魔方状态'},
        ),
        migrations.AlterModelOptions(
            name='formula',
            options={'ordering': ['category', 'name'], 'verbose_name': '公式', 'verbose_name_plural': '公式'},
        ),
        migrations.AlterModelOptions(
            name='formulacollection',
            options={'verbose_name': '公式收藏', 'verbose_name_plural': '公式收藏'},
        ),
        migrations.AlterModelOptions(
            name='formulatag',
            options={'verbose_name': '公式标签', 'verbose_name_plural': '公式标签'},
        ),
    ]
