# Generated by Django 6.0.7 on 2026-07-29 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0003_alter_cubecategory_options_alter_cubestate_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cubecategory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cubecategory',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='创建者（为空表示系统预置分类）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cubecategory',
            name='is_custom',
            field=models.BooleanField(default=False, verbose_name='是否自定义'),
        ),
    ]
