# Generated by Django 6.0.5 on 2026-07-19 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cube_type', models.CharField(choices=[('2x2', '二阶魔方'), ('3x3', '三阶魔方'), ('4x4', '四阶魔方'), ('5x5', '五阶魔方'), ('other', '其他')], default='3x3', max_length=10, verbose_name='魔方类型')),
                ('method', models.CharField(choices=[('layer', '层先法'), ('cfop', 'CFOP'), ('roux', '桥式'), ('zbll', 'ZBLL'), ('other', '其他')], default='layer', max_length=20, verbose_name='还原方法')),
                ('time_ms', models.IntegerField(verbose_name='还原时间(毫秒)')),
                ('scramble', models.TextField(blank=True, verbose_name='打乱公式')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timer_records', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'db_table': 'timer_record',
                'ordering': ['-created_at'],
            },
        ),
    ]
