# Generated by Django 6.0.5 on 2026-07-24 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timerrecord',
            options={'ordering': ['-created_at'], 'verbose_name': '计时记录', 'verbose_name_plural': '计时记录'},
        ),
    ]
