# Generated by Django 6.0.5 on 2026-09-10 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0002_alter_timerrecord_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='timerrecord',
            name='is_dnf',
            field=models.BooleanField(default=False, verbose_name='是否 DNF'),
        ),
        migrations.AddField(
            model_name='timerrecord',
            name='move_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='复原步数'),
        ),
        migrations.AddField(
            model_name='timerrecord',
            name='observation_time_ms',
            field=models.IntegerField(blank=True, null=True, verbose_name='观察时间(毫秒)'),
        ),
        migrations.AddField(
            model_name='timerrecord',
            name='solve_sequence',
            field=models.TextField(blank=True, null=True, verbose_name='复原步骤序列'),
        ),
        migrations.AddField(
            model_name='timerrecord',
            name='timing_mode',
            field=models.CharField(choices=[('manual', '手动计时'), ('smart', '智能魔方')], default='manual', max_length=10, verbose_name='计时方式'),
        ),
        migrations.CreateModel(
            name='SmartCubeDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=20, verbose_name='MAC 地址')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='设备名称')),
                ('last_connected_at', models.DateTimeField(blank=True, null=True, verbose_name='最后连接时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smart_cube_devices', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '智能魔方设备',
                'verbose_name_plural': '智能魔方设备',
                'db_table': 'smart_cube_device',
                'ordering': ['-last_connected_at'],
            },
        ),
        migrations.AddField(
            model_name='timerrecord',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='timer.smartcubedevice', verbose_name='关联设备'),
        ),
        migrations.AddConstraint(
            model_name='smartcubedevice',
            constraint=models.UniqueConstraint(fields=('user', 'mac_address'), name='unique_user_mac'),
        ),
    ]
