# Generated by Django 6.0.5 on 2026-06-05 09:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='标签名')),
                ('color', models.CharField(default='#1890ff', help_text='十六进制颜色码', max_length=7, verbose_name='颜色')),
                ('use_count', models.IntegerField(default=0, verbose_name='使用次数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'db_table': 'forum_tag',
                'ordering': ['-use_count'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='标题')),
                ('content', models.TextField(verbose_name='正文')),
                ('content_md', models.TextField(blank=True, help_text='支持上传.md文件', verbose_name='Markdown源码')),
                ('view_count', models.IntegerField(default=0, verbose_name='浏览量')),
                ('like_count', models.IntegerField(default=0, verbose_name='点赞数')),
                ('comment_count', models.IntegerField(default=0, verbose_name='评论数')),
                ('collect_count', models.IntegerField(default=0, verbose_name='收藏数')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='置顶')),
                ('is_essence', models.BooleanField(default=False, verbose_name='精华')),
                ('is_closed', models.BooleanField(default=False, verbose_name='关闭评论')),
                ('status', models.CharField(choices=[('published', '已发布'), ('deleted', '已删除'), ('draft', '草稿')], default='published', max_length=20, verbose_name='状态')),
                ('report_count', models.IntegerField(default=0, verbose_name='举报数')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '帖子',
                'verbose_name_plural': '帖子',
                'db_table': 'forum_post',
                'ordering': ['-is_pinned', '-is_essence', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='内容')),
                ('like_count', models.IntegerField(default=0, verbose_name='点赞数')),
                ('dislike_count', models.IntegerField(default=0, verbose_name='点踩数')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='是否隐藏（被举报）')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='评论者')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='forum.comment', verbose_name='父评论')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='forum.post', verbose_name='所属帖子')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'forum_comment',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_tags', to='forum.post')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_posts', to='forum.tag')),
            ],
            options={
                'verbose_name': '帖子标签',
                'verbose_name_plural': '帖子标签',
                'db_table': 'forum_post_tags',
                'unique_together': {('post', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', through='forum.PostTag', to='forum.tag', verbose_name='标签'),
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField(default=True, verbose_name='是否点赞')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='forum.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'forum_comment_like',
                'unique_together': {('comment', 'user')},
            },
        ),
        migrations.CreateModel(
            name='PostCollect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collects', to='forum.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'forum_post_collect',
                'unique_together': {('post', 'user')},
            },
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='forum.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'forum_post_like',
                'unique_together': {('post', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('post', '帖子'), ('comment', '评论')], max_length=20, verbose_name='内容类型')),
                ('object_id', models.IntegerField(verbose_name='内容ID')),
                ('reason', models.CharField(choices=[('spam', '垃圾广告'), ('violence', '暴力内容'), ('harassment', '人身攻击'), ('illegal', '违法违规'), ('other', '其他')], max_length=20, verbose_name='举报原因')),
                ('description', models.TextField(blank=True, verbose_name='详细描述')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('approved', '已处理'), ('rejected', '已驳回')], default='pending', max_length=20, verbose_name='处理状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('handler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_reports', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='举报人')),
            ],
            options={
                'verbose_name': '举报',
                'verbose_name_plural': '举报',
                'db_table': 'forum_report',
                'unique_together': {('content_type', 'object_id', 'reporter')},
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author', '-created_at'], name='forum_post_author__f7ff0a_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created_at'], name='forum_post_created_543ce4_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['status', '-created_at'], name='forum_post_status_56aec8_idx'),
        ),
    ]
