# Generated by Django 6.0.5 on 2026-07-24 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_postimage_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentlike',
            options={'verbose_name': '评论点赞', 'verbose_name_plural': '评论点赞'},
        ),
        migrations.AlterModelOptions(
            name='postcollect',
            options={'verbose_name': '帖子收藏', 'verbose_name_plural': '帖子收藏'},
        ),
        migrations.AlterModelOptions(
            name='postlike',
            options={'verbose_name': '帖子点赞', 'verbose_name_plural': '帖子点赞'},
        ),
    ]
