# Generated by Django 6.0.5 on 2026-07-24 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': '购物车', 'verbose_name_plural': '购物车'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': '订单', 'verbose_name_plural': '订单'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': '订单明细', 'verbose_name_plural': '订单明细'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': '商品分类', 'verbose_name_plural': '商品分类'},
        ),
    ]
